In [16]:
import pandas as pd
import numpy as np
from io import StringIO

In [8]:
df=pd.read_csv("aug_train.csv")

# 2.read file from url

In [22]:
import requests
from io import StringIO
url="https://raw.githubusercontent.com/aishwaryamate/Datasets/refs/heads/main/AirPassengers.csv"
req=requests.get(url)
data=StringIO(req.text)
data.readlines()

['Month,Passengers\n',
 '1949-01,112\n',
 '1949-02,118\n',
 '1949-03,132\n',
 '1949-04,129\n',
 '1949-05,121\n',
 '1949-06,135\n',
 '1949-07,148\n',
 '1949-08,148\n',
 '1949-09,136\n',
 '1949-10,119\n',
 '1949-11,104\n',
 '1949-12,118\n',
 '1950-01,115\n',
 '1950-02,126\n',
 '1950-03,141\n',
 '1950-04,135\n',
 '1950-05,125\n',
 '1950-06,149\n',
 '1950-07,170\n',
 '1950-08,170\n',
 '1950-09,158\n',
 '1950-10,133\n',
 '1950-11,114\n',
 '1950-12,140\n',
 '1951-01,145\n',
 '1951-02,150\n',
 '1951-03,178\n',
 '1951-04,163\n',
 '1951-05,172\n',
 '1951-06,178\n',
 '1951-07,199\n',
 '1951-08,199\n',
 '1951-09,184\n',
 '1951-10,162\n',
 '1951-11,146\n',
 '1951-12,166\n',
 '1952-01,171\n',
 '1952-02,180\n',
 '1952-03,193\n',
 '1952-04,181\n',
 '1952-05,183\n',
 '1952-06,218\n',
 '1952-07,230\n',
 '1952-08,242\n',
 '1952-09,209\n',
 '1952-10,191\n',
 '1952-11,172\n',
 '1952-12,194\n',
 '1953-01,196\n',
 '1953-02,196\n',
 '1953-03,236\n',
 '1953-04,235\n',
 '1953-05,229\n',
 '1953-06,243\n',
 '1953-07,264\n',
 '1953-08,272\n',
 '1953-09,237\n',
 '1953-10,211\n',
 '1953-11,180\n',
 '1953-12,201\n',
 '1954-01,204\n',
 '1954-02,188\n',
 '1954-03,235\n',
 '1954-04,227\n',
 '1954-05,234\n',
 '1954-06,264\n',
 '1954-07,302\n',
 '1954-08,293\n',
 '1954-09,259\n',
 '1954-10,229\n',
 '1954-11,203\n',
 '1954-12,229\n',
 '1955-01,242\n',
 '1955-02,233\n',
 '1955-03,267\n',
 '1955-04,269\n',
 '1955-05,270\n',
 '1955-06,315\n',
 '1955-07,364\n',
 '1955-08,347\n',
 '1955-09,312\n',
 '1955-10,274\n',
 '1955-11,237\n',
 '1955-12,278\n',
 '1956-01,284\n',
 '1956-02,277\n',
 '1956-03,317\n',
 '1956-04,313\n',
 '1956-05,318\n',
 '1956-06,374\n',
 '1956-07,413\n',
 '1956-08,405\n',
 '1956-09,355\n',
 '1956-10,306\n',
 '1956-11,271\n',
 '1956-12,306\n',
 '1957-01,315\n',
 '1957-02,301\n',
 '1957-03,356\n',
 '1957-04,348\n',
 '1957-05,355\n',
 '1957-06,422\n',
 '1957-07,465\n',
 '1957-08,467\n',
 '1957-09,404\n',
 '1957-10,347\n',
 '1957-11,305\n',
 '1957-12,336\n',
 '1958-01,340\n',
 '1958-02,318\n',
 '1958-03,362\n',
 '1958-04,348\n',
 '1958-05,363\n',
 '1958-06,435\n',
 '1958-07,491\n',
 '1958-08,505\n',
 '1958-09,404\n',
 '1958-10,359\n',
 '1958-11,310\n',
 '1958-12,337\n',
 '1959-01,360\n',
 '1959-02,342\n',
 '1959-03,406\n',
 '1959-04,396\n',
 '1959-05,420\n',
 '1959-06,472\n',
 '1959-07,548\n',
 '1959-08,559\n',
 '1959-09,463\n',
 '1959-10,407\n',
 '1959-11,362\n',
 '1959-12,405\n',
 '1960-01,417\n',
 '1960-02,391\n',
 '1960-03,419\n',
 '1960-04,461\n',
 '1960-05,472\n',
 '1960-06,535\n',
 '1960-07,622\n',
 '1960-08,606\n',
 '1960-09,508\n',
 '1960-10,461\n',
 '1960-11,390\n',
 '1960-12,432\n']

## 3. if file is tsv("tab seprated value") then we can use sep parameter in read_csv function

In [25]:
df=pd.read_csv("titanic.tsv",sep="\t")
df

,1,0,3,"Braund, Mr. Owen Harris",male,22,1.1,0.1,A/5 21171,7.25,\N,S
0,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
1,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,\N,S
2,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,C123,S
3,5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,\N,S
4,6,0,3,"Moran, Mr. James",male,\N,0,0,330877,8.4583,\N,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
885,887,0,2,"Montvila, Rev. Juozas",male,27,0,0,211536,13.0000,\N,S
886,888,1,1,"Graham, Miss. Margaret Edith",female,19,0,0,112053,30.0000,B42,S
887,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,\N,1,2,W./C. 6607,23.4500,\N,S
888,890,1,1,"Behr, Mr. Karl Howell",male,26,0,0,111369,30.0000,C148,C
889,891,0,3,"Dooley, Mr. Patrick",male,32,0,0,370376,7.7500,\N,Q

###### As you see that first row atomatic convert into column .To handle this problem we require parameter nmaes to give a columns

In [27]:
df=pd.read_csv("titanic.tsv",sep="\t",names=['a','b','c','d','e','f','g','h','i','k','l','m'])
df

,a,b,c,d,e,f,g,h,i,k,l,m
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,\N,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,\N,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,\N,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27,0,0,211536,13.0000,\N,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,\N,1,2,W./C. 6607,23.4500,\N,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32,0,0,370376,7.7500,\N,Q