In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("Social_Network_Ads.csv")
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [3]:
df["Male"]=df["Gender"].apply(lambda x:1 if x=="Male" else 0)
df["Female"]=df["Gender"].apply(lambda x:1 if x=="Female" else 0)

In [7]:
df=df.drop("Gender",axis=1)

In [8]:
df.rename(columns={"EstimatedSalary":"Est_sal"})

      User ID  Age  Est_sal  Purchased  Male  Female
0    15624510   19    19000          0     1       0
1    15810944   35    20000          0     1       0
2    15668575   26    43000          0     0       1
3    15603246   27    57000          0     0       1
4    15804002   19    76000          0     1       0
..        ...  ...      ...        ...   ...     ...
395  15691863   46    41000          1     0       1
396  15706071   51    23000          1     1       0
397  15654296   50    20000          1     0       1
398  15755018   36    33000          0     1       0
399  15594041   49    36000          1     0       1

[400 rows x 6 columns]

In [23]:
# from sklearn.model_selection import train_test_split
# y=df["Purchased"]
# x=df.drop("Purchased",axis=1)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [24]:
x_train

      User ID  Age  EstimatedSalary  Male  Female
336  15664907   58           144000     1       0
64   15605000   59            83000     0       1
55   15649136   24            55000     0       1
106  15706185   26            35000     0       1
300  15736397   58            38000     0       1
..        ...  ...              ...   ...     ...
323  15619465   48            30000     0       1
192  15779581   29            43000     1       0
117  15591433   36            52000     1       0
47   15776348   27            54000     0       1
172  15794661   26           118000     0       1

[320 rows x 5 columns]

Purchased
0    257
1    143
Name: count, dtype: int64