In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [7]:
df=pd.read_csv("customer.csv")
df.sample(5)

    age  gender   review education purchased
13   57  Female  Average    School        No
12   51    Male     Poor    School        No
8    65  Female  Average        UG        No
32   92    Male  Average        UG       Yes
43   27    Male     Poor        PG        No

In [18]:
l=list(df["review"].unique())
l

['Average', 'Poor', 'Good']

In [8]:
df=df.iloc[:,2:]

    review education purchased
0  Average    School        No

In [9]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split((df.drop(columns="purchased")),df["purchased"],test_size=0.2)

In [13]:
print(len(X_train))
print(len(X_test))

40
10

In [14]:
from sklearn.preprocessing import OrdinalEncoder
encode=OrdinalEncoder(categories=[["Poor","Average","Good"],["School","UG","PG"]])
encode.fit(X_test)
X_train_encode=encode.transform(X_train)
X_test_encode=encode.transform(X_test)

In [21]:
X_train_encode=pd.DataFrame(X_train_encode,columns=X_train.columns)
X_test_encode=pd.DataFrame(X_test_encode,columns=X_test.columns)

In [22]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
le.fit(y_test)
y_train_encode=le.transform(y_train)
y_test_encode=le.transform(y_test)
y_test_encode

array([1, 1, 0, 1, 1, 1, 1, 1, 1, 0])

In [24]:
y_test_encode=pd.DataFrame(y_test_encode,columns=[["purchased"]])
y_train_encode=pd.DataFrame(y_train_encode,columns=[["purchased"]])

In [25]:
y_test_encode

  purchased
0         1
1         1
2         0
3         1
4         1
5         1
6         1
7         1
8         1
9         0